NumberOfGames: 100000
NumberOfThreads: 12
Rules:
  PlusStackConvention: Conservative
  DrawUntilPlayable: false
Players:
  - Name: Cal Crosby
    Strategy:
      Path: C:\Users\Glizzus\Projects\unifico-c#\Unifico\Unifico.Plugins\PreferFaceStrategy.cs  
  - Name: Payden Whiting
  - Name: Conner Runion
