$schema: http://json-schema.org/draft-07/schema#
title: UnificoConfig 
type: object
properties:
  NumberOfGames:
    type: integer
    minimum: 0
  NumberOfThreads:
    type: integer
    minimum: 1
  Rules:
    type: object
    properties:
      PlusStackConvention:
        type: string
        enum: [Conservative, Banned, Liberal]
      DrawUntilPlayable:
        type: boolean
  Players:
    type: array
    items:
      type: object
      properties:
        Name:
          type: string
        Strategy:
          type: string
        StrategyPath:
          type: string
      oneOf:
        - required:
          - Strategy
        - required:
          - StrategyPath


required:
  - NumberOfGames
  - Players
